- name: Use docker compose to run all containers
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3.10  # Specify the Python interpreter path

  tasks:
    - name: Start docker service
      service:
        name: docker
        state: started

    - name: Copy Docker Compose file
      copy:
        src: docker-compose.yml
        dest: ./

    - name: Run docker compose up command
      become: true
      docker_compose:
        project_src: ./
        state: present
        pull: yes

