server:
  port: 8083
spring:
  application:
    name: API-GATEWAY
  config:
    import: optional:configserver:http://localhost:8084
  cloud:
    gateway:
      routes:
      - id: EMPLOYEE-SERVICE
        uri: lb://EMPLOYEE-SERVICE
        predicates:
        - Path=/employee/**,/auth/**

      - id: DEPARTMENT-SERVICE
        uri: lb://DEPARTMENT-SERVICE
        predicates:
          - Path=/department/**
