server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Emp_service_without?createDatabaseIfNotExist=true
    username: root
    password: Admin123
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: EMPLOYEE-SERVICE
  config:
    import: optional:configserver:http://localhost:8084
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
