server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Emp_service?createDatabaseIfNotExist=true
    username: root
    password: Admin123
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: Employee-Service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka